### ISSUE TITLE
Error related to import of WorldCat source

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#112]
Error produced by entering WorldCat URL into the appropriate field and then clicking on "create collection", which did create the collection but hung for some time. Is it possible that this is related to what appears to be WorldCat's abandonment of VIAF for authors in favor of its own thesaurus (see JSON-LD produced by that collection creation, which I've copied below the error message)? Or are we agnostic about the vocabulary used for the creator?

Time: 6/17/2016, 11:31:06 AM
Version: 2.4.2
# Page: #/p/jon_test/periodCollections/https%3A%2F%2Ftest.perio.do%2F.well-known%2Fgenid%2F54cb5c16a23d6495bf77f2b29e91110b/

TypeError: Invalid attempt to destructure non-iterable instance
    at https://test.perio.do/dist/periodo-2.4.2.min.js:77:22325
    at Constructor.getHiddenRange (https://test.perio.do/dist/periodo-2.4.2.min.js:77:23491)
    at Constructor.render (https://test.perio.do/dist/periodo-2.4.2.min.js:77:24702)
    at _renderValidatedComponentWithoutOwnerOrContext (https://test.perio.do/dist/periodo-2.4.2.min.js:66:11267)
    at _renderValidatedComponent (https://test.perio.do/dist/periodo-2.4.2.min.js:66:11557)
    at _updateRenderedComponent (https://test.perio.do/dist/periodo-2.4.2.min.js:66:10332)
    at _performComponentUpdate (https://test.perio.do/dist/periodo-2.4.2.min.js:66:9904)
    at updateComponent (https://test.perio.do/dist/periodo-2.4.2.min.js:66:8747)
    at performUpdateIfNecessary (https://test.perio.do/dist/periodo-2.4.2.min.js:66:7655)
    at Object.performUpdateIfNecessary (https://test.perio.do/dist/periodo-2.4.2.min.js:69:13027)

"id": "https://test.perio.do/.well-known/genid/54cb5c16a23d6495bf77f2b29e91110b",
  "source": {
    "locator": "p. 320",
    "partOf": {
      "contributors": [],
      "creators": [
        {
          "id": "http://experiment.worldcat.org/entity/work/data/1155489236#Person/gibbon_edward_1737_1794",
          "name": "Edward Gibbon"
        }
      ],
      "id": "http://www.worldcat.org/oclc/5181145",
      "title": "The history of the decline and fall of the Roman empire.",
      "yearPublished": "1830"

**Comment by atomrab** [comment]
Couldn't replicate today, by the way. WorldCat link allowed new collection to be saved without a problem.
