### ISSUE TITLE
Hard refresh breaks period view/edit

### ISSUE THREAD

**Issue by rybesh** [periodo/periodo-client#179]
A hard refresh of e.g. http://0.0.0.0:5002/?page=period-view&backendID=web-https%3A%2F%2Fdata.staging.perio.do&authorityID=p03wskd&periodID=p03wskd4mmt results in:
```
TypeError: Cannot read property 'periods' of undefined
    at ResourceGroup:Period:mapStateToProps (http://0.0.0.0:5002/periodo-client.js:12904:31)
    at http://0.0.0.0:5002/periodo-client.js:13003:41
    at Array.reduce (<anonymous>)
    at Function.Resource:period-view:combinedMapStateToProps [as mapToProps] (http://0.0.0.0:5002/periodo-client.js:13002:43)
    at mapToPropsProxy (http://0.0.0.0:5002/periodo-client.js:224907:46)
    at Function.detectFactoryAndVerify (http://0.0.0.0:5002/periodo-client.js:224916:19)
    at mapToPropsProxy (http://0.0.0.0:5002/periodo-client.js:224907:46)
    at handleFirstCall (http://0.0.0.0:5002/periodo-client.js:224760:18)
    at pureFinalPropsSelector (http://0.0.0.0:5002/periodo-client.js:224801:81)
    at Object.runComponentSelector [as run] (http://0.0.0.0:5002/periodo-client.js:224224:25)

in Connect(ResourceLoader) (created by BackendKnower)
    in BackendKnower (created by Connect(BackendKnower))
    in Connect(BackendKnower) (created by Resource:period-view)
    in div (created by Clean.div)
    in Clean.div (created by UI:Box)
    in UI:Box (created by Resource:period-view)
    in Resource:period-view (created by ORGShell)
    in div (created by Clean.div)
    in Clean.div (created by UI:Box)
    in UI:Box (created by MenuedResource)
    in div (created by Clean.div)
    in Clean.div (created by UI:Box)
    in UI:Box (created by MenuedResource)
    in MenuedResource (created by PeriodoApplication)
    in div (created by Clean.div)
    in Clean.div (created by UI:Box)
    in UI:Box (created by PeriodoApplication)
    in div (created by Clean.div)
    in Clean.div (created by UI:Grid)
    in UI:Grid (created by PeriodoApplication)
    in ThemeProvider (created by PeriodoApplication)
    in PeriodoApplication (created by ORGShell)
    in ORGShell (created by Shell)
    in ThemeProvider (created by Shell)
    in Provider (created by Shell)
    in Shell
```

**Comment by ptgolden** [comment]
Ah, dangit. I'll check this out this afternoon or next.

**Comment by rybesh** [comment]
This is no longer happening; must have been fixed by something else you checked in.
