### ISSUE TITLE
Can't reject patch with broken logic

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#267]
David Novak submitted a patch that then broke because he had removed a parent period but not the child periods (currently patch #4). He successfully resubmitted after fixing the problem, and I successfully merged that patch -- but I can't merge the bad patch, because every time I try to open it, it generates the following error: 

Error stack
TypeError: Cannot read property 'Symbol(RelatedPeriods)' of undefined
    at https://client.perio.do/periodo-client-4.4.3.min.js:18:17964
    at Array.forEach (<anonymous>)
    at https://client.perio.do/periodo-client-4.4.3.min.js:18:17792
    at Array.forEach (<anonymous>)
    at https://client.perio.do/periodo-client-4.4.3.min.js:18:17700
    at Array.forEach (<anonymous>)
    at module.exports (https://client.perio.do/periodo-client-4.4.3.min.js:18:17673)
    at new module.exports (https://client.perio.do/periodo-client-4.4.3.min.js:18:16077)
    at https://client.perio.do/periodo-client-4.4.3.min.js:120:19497
    at async throwIfUnsuccessful (https://client.perio.do/periodo-client-4.4.3.min.js:120:36776)
Component stack
in F
    in Unknown
    in Unknown
    in ConnectFunction
    in div
    in Clean.div
    in UI:Box
    in Resource:review-patch
    in div
    in Clean.div
    in UI:Box
    in div
    in Clean.div
    in UI:Box
    in MenuedResource
    in div
    in Clean.div
    in UI:Box
    in div
    in Clean.div
    in UI:Grid
    in ThemeProvider
    in PeriodoApplication
    in F
    in ThemeProvider
    in Provider
    in Unknown

@rybesh, can you reject from the server side?

**Comment by ptgolden** [comment]
I'm going to:

1) Add `componentDidCatch` to the patch visualization that has an error message if something like this pops up in the future. That way, even if there's something wonky going on, the patch can still be rejected.

2) When generating a patch, go over every period's related periods to make sure there aren't any periods that won't be present when applying the patch

**Comment by ptgolden** [comment]
The problem Adam ran into was fixed by the above PR, specifically this addition:

https://github.com/periodo/periodo-client/blob/dae853c7663db8e5a4719b30dac40ba018d0305d/modules/periodo-app/src/backends/dataset_proxy/index_items.js#L49-L51

...but I'll still add a `componentDidCatch` in case there's something weird in the future
