### ISSUE TITLE
Regular outages when reloading data to local IDB after a save

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#287]
I am not sure if this is actually a server issue, but since it happened to all of us at the same time during the last call we had, I am assuming it's not just my local browser (it also happens across all my browsers at once, regardless of the datasource). 

As I have been going through the LCSH to clean up spatial coverage, I am getting the following error at fairly regular, roughly 20-minute intervals. It persists for about three to seven minutes and then the client loads as normal (the last save is ignored).

Client error
Error stack
OpenFailedError: UnknownError Internal error opening backing store for indexedDB.open.
    at Transaction.create (https://client.perio.do/periodo-client-4.4.3.min.js:123:515822)
    at https://client.perio.do/periodo-client-4.4.3.min.js:123:516784
    at executePromiseTask (https://client.perio.do/periodo-client-4.4.3.min.js:123:473816)
    at new Promise (https://client.perio.do/periodo-client-4.4.3.min.js:123:474362)
    at https://client.perio.do/periodo-client-4.4.3.min.js:123:516620
    at usePSD (https://client.perio.do/periodo-client-4.4.3.min.js:123:481992)
    at newScope (https://client.perio.do/periodo-client-4.4.3.min.js:123:481839)
    at Transaction._promise (https://client.perio.do/periodo-client-4.4.3.min.js:123:516581)
Component stack
in F
    in Unknown
    in Unknown
    in ConnectFunction
    in div
    in Clean.div
    in UI:Box
    in Resource:backend-home
    in div
    in Clean.div
    in UI:Box
    in div
    in Clean.div
    in UI:Box
    in MenuedResource
    in div
    in Clean.div
    in UI:Box
    in div
    in Clean.div
    in UI:Grid
    in ThemeProvider
    in PeriodoApplication
    in F
    in ThemeProvider
    in Provider
    in Unknown

**Comment by rybesh** [comment]
@atomrab This is a client issue (I think) so I moved the issue.

**Comment by rybesh** [comment]
Oh, also: @atomrab are you using client.perio.do or client.staging.perio.do?

**Comment by ptgolden** [comment]
This is a very strange. Just out of curiosity- how much free space do you have on your hard drive?

**Comment by ptgolden** [comment]
Also, next time this happens to you, can you copy the error from another browser? I am wondering if it will have the same error (`UnknownError Internal error opening backing store for indexedDB.open`).
