### ISSUE TITLE
Error caused by attempt to save edited period definition in local IDB

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#81]
I'm not sure what this is connected to -- I've been adding a period collection and editing period definitions. The error message has appeared three times.

Time: 8/5/2015, 2:02:55 PM
Version: 2.0.1
Page: #/p/trying_again_test/periodCollections/p0f65r2/
=========
TypeError: this.state.alternateLabels.unshift is not a function
    at module.exports.React.createClass.getValue (https://test.perio.do/dist/periodo-2.0.1.min.js:76:16366)
    at module.exports.React.createClass.getPeriodValue (https://test.perio.do/dist/periodo-2.0.1.min.js:76:11253)
    at module.exports.React.createClass.handleSave (https://test.perio.do/dist/periodo-2.0.1.min.js:76:4190)
    at Object.executeDispatch (https://test.perio.do/dist/periodo-2.0.1.min.js:63:29601)
    at SimpleEventPlugin.executeDispatch (https://test.perio.do/dist/periodo-2.0.1.min.js:71:1875)
    at forEachEventDispatch (https://test.perio.do/dist/periodo-2.0.1.min.js:63:29447)
    at Object.executeDispatchesInOrder (https://test.perio.do/dist/periodo-2.0.1.min.js:63:29711)
    at executeDispatchesAndRelease (https://test.perio.do/dist/periodo-2.0.1.min.js:63:20777)
    at Array.forEach (native)
    at forEachAccumulated (https://test.perio.do/dist/periodo-2.0.1.min.js:71:26724)
    at Object.EventPluginHub.processEventQueue (https://test.perio.do/dist/periodo-2.0.1.min.js:63:22948)

**Comment by atomrab** [comment]
Update: this error occurs when one edits a period definition and hits "Save". In the interface, nothing happens (the window doesn't close, no indication that the value is saved; can only leave editing interface with return to PeriodO or cancel button). Multiple errors probably from me hitting "Save" multiple times. The edited value is NOT saved when one backs out to the browse view.

Time: 8/5/2015, 2:02:55 PM
Version: 2.0.1
Page: #/p/trying_again_test/periodCollections/p0f65r2/
=========
TypeError: this.state.alternateLabels.unshift is not a function
    at module.exports.React.createClass.getValue (https://test.perio.do/dist/periodo-2.0.1.min.js:76:16366)
    at module.exports.React.createClass.getPeriodValue (https://test.perio.do/dist/periodo-2.0.1.min.js:76:11253)
    at module.exports.React.createClass.handleSave (https://test.perio.do/dist/periodo-2.0.1.min.js:76:4190)
    at Object.executeDispatch (https://test.perio.do/dist/periodo-2.0.1.min.js:63:29601)
    at SimpleEventPlugin.executeDispatch (https://test.perio.do/dist/periodo-2.0.1.min.js:71:1875)
    at forEachEventDispatch (https://test.perio.do/dist/periodo-2.0.1.min.js:63:29447)
    at Object.executeDispatchesInOrder (https://test.perio.do/dist/periodo-2.0.1.min.js:63:29711)
    at executeDispatchesAndRelease (https://test.perio.do/dist/periodo-2.0.1.min.js:63:20777)
    at Array.forEach (native)
    at forEachAccumulated (https://test.perio.do/dist/periodo-2.0.1.min.js:71:26724)
    at Object.EventPluginHub.processEventQueue (https://test.perio.do/dist/periodo-2.0.1.min.js:63:22948)

**Comment by ptgolden** [comment]
Hey Adam,

Can you tell me- are these periods ones that you made before I release the 2.0.0 version the other day? I have a hunch that's what's causing this. We changed the way labels are expressed in the linked data, and it looks like the period you're trying to edit is expecting the old way.

If you have any backends that you've added a lot of periods to, send me a dump of them and I can manually fix them up and send them back to you. Otherwise, you'll need to start from fresh backends. Sorry about the annoyance- Ryan and I have settled 100% on the data model now, so this won't happen again.

**Comment by atomrab** [comment]
Eeeeeh. I have bad news, then. This is happening in a collection I just made two hours ago, in an IDB I made just before that. The interface was behaving a little erratically (not reacting to clicks on definitions, not reacting to a click on the switch backend button, etc), and so I cleared everything -- everything, the whole column of checkboxes on the Chrome clear browsing history dialog -- and started from scratch (I cleared out all of the local idbs I had). I'll send you the json file for the local idb I just made, and you can take a look at it (we don't need to save it -- I added one period to an existing collection, edited one period -- the editing worked the first time, just not after that -- and added one new collection with one new period). I just tried to edit a period again in this idb and got the same message.

I did build this new idb by syncing a couple of existing collections from the server, and then adding my own. Could it be the server side data?

Time: 8/5/2015, 3:32:43 PM
Version: 2.1.0
Page: #/p/trying_again_test/periodCollections/https%3A%2F%2Ftest.perio.do%2F.well-known%2Fgenid%2F1e4ca26ab04be6b0e2cdb3aae2d596e5/
=========
TypeError: this.state.alternateLabels.unshift is not a function
    at module.exports.React.createClass.getValue (https://test.perio.do/dist/periodo-2.1.0.min.js:76:17296)
    at module.exports.React.createClass.getPeriodValue (https://test.perio.do/dist/periodo-2.1.0.min.js:76:12183)
    at module.exports.React.createClass.handleSave (https://test.perio.do/dist/periodo-2.1.0.min.js:76:5120)
    at Object.executeDispatch (https://test.perio.do/dist/periodo-2.1.0.min.js:63:29601)
    at SimpleEventPlugin.executeDispatch (https://test.perio.do/dist/periodo-2.1.0.min.js:71:1875)
    at forEachEventDispatch (https://test.perio.do/dist/periodo-2.1.0.min.js:63:29447)
    at Object.executeDispatchesInOrder (https://test.perio.do/dist/periodo-2.1.0.min.js:63:29711)
    at executeDispatchesAndRelease (https://test.perio.do/dist/periodo-2.1.0.min.js:63:20777)
    at Array.forEach (native)
    at forEachAccumulated (https://test.perio.do/dist/periodo-2.1.0.min.js:71:26724)

**Comment by atomrab** [comment]
Actually, let me add some information. I created a brand-new local idb from nothing, synced a couple of collections from the main dataset, edited one definition in those and added another, and then made my own new collection, to which I added one definition.

THEN I made a new idb and synced it with an existing json file that I had exported from my pre-8/3 local idb. That second idb, into which the old idb data was loaded, is now acting really funny (failing to expand when I click on period definitions, etc). So maybe loading the old one is causing some sort of error loop, both for itself and for the new one I made? 

I'm sending both to you by email. It would be great if you could save trying_again_test, but if you can't, I will start over (but would like to diagnose the problem first).

**Comment by sarahab** [comment]
I tried to edit a period today, in a local IDB created August 11 - specifically, refining the Spatial coverage description - and got the following errors:

8/18/2015, 11:54:55 AM
TypeError: this.state.alternateLabels.unshift is not a function

Time: 8/18/2015, 11:54:55 AMVersion: 2.1.0Page: #/p/August11/periodCollections/https://test.perio.do/.well-known/genid/7a61f1e91e7b50423daa2f4aed6eb6ed/=========[403]</module.exports<.getValue@https://test.perio.do/dist/periodo-2.1.0.min.js:76:17269[402]</module.exports<.getPeriodValue@https://test.perio.do/dist/periodo-2.1.0.min.js:76:12163[400]</module.exports<.handleSave@https://test.perio.do/dist/periodo-2.1.0.min.js:76:5101executeDispatch@https://test.perio.do/dist/periodo-2.1.0.min.js:63:29601[307]</</SimpleEventPlugin.executeDispatch@https://test.perio.do/dist/periodo-2.1.0.min.js:71:1858forEachEventDispatch@https://test.perio.do/dist/periodo-2.1.0.min.js:63:29447executeDispatchesInOrder@https://test.perio.do/dist/periodo-2.1.0.min.js:63:29711[220]</</executeDispatchesAndRelease@https://test.perio.do/dist/periodo-2.1.0.min.js:63:20760[338]</forEachAccumulated@https://test.perio.do/dist/periodo-2.1.0.min.js:71:26720[220]</</EventPluginHub.processEventQueue@https://test.perio.do/dist/periodo-2.1.0.min.js:63:22948runEventQueueInBatch@https://test.perio.do/dist/periodo-2.1.0.min.js:68:278[269]</ReactEventEmitterMixin.handleTopLevel@https://test.perio.do/dist/periodo-2.1.0.min.js:68:564handleTopLevelImpl@https://test.perio.do/dist/periodo-2.1.0.min.js:68:1478[319]</</Mixin.perform@https://test.perio.do/dist/periodo-2.1.0.min.js:71:14429[261]</ReactDefaultBatchingStrategy.batchedUpdates@https://test.perio.do/dist/periodo-2.1.0.min.js:67:5164batchedUpdates@https://test.perio.do/dist/periodo-2.1.0.min.js:70:16563[270]</ReactEventListener.dispatchEvent@https://test.perio.do/dist/periodo-2.1.0.min.js:68:3383

Also: 
8/18/2015, 11:54:43 AM
TypeError: prev.alternateLabels.set is not a function

Time: 8/18/2015, 11:54:43 AMVersion: 2.1.0Page: #/p/August11/periodCollections/https://test.perio.do/.well-known/genid/7a61f1e91e7b50423daa2f4aed6eb6ed/=========[403]</module.exports<.handleAlternateLabelChange/<@https://test.perio.do/dist/periodo-2.1.0.min.js:76:17671[245]</</ReactCompositeComponentMixin._processPendingState@https://test.perio.do/dist/periodo-2.1.0.min.js:65:30353[245]</</ReactCompositeComponentMixin.updateComponent@https://test.perio.do/dist/periodo-2.1.0.min.js:65:29182[284]</</ReactPerf.measure/wrapper@https://test.perio.do/dist/periodo-2.1.0.min.js:69:8325[245]</</ReactCompositeComponentMixin.performUpdateIfNecessary@https://test.perio.do/dist/periodo-2.1.0.min.js:65:27844[291]</</ReactReconciler.performUpdateIfNecessary@https://test.perio.do/dist/periodo-2.1.0.min.js:69:21345runBatchedUpdates@https://test.perio.do/dist/periodo-2.1.0.min.js:70:17197[319]</</Mixin.perform@https://test.perio.do/dist/periodo-2.1.0.min.js:71:14429[319]</</Mixin.perform@https://test.perio.do/dist/periodo-2.1.0.min.js:71:14429[302]</</<.perform@https://test.perio.do/dist/periodo-2.1.0.min.js:70:19475[302]</</flushBatchedUpdates@https://test.perio.do/dist/periodo-2.1.0.min.js:70:19808[284]</</ReactPerf.measure/wrapper@https://test.perio.do/dist/periodo-2.1.0.min.js:69:8325[319]</</Mixin.closeAll@https://test.perio.do/dist/periodo-2.1.0.min.js:71:15472[319]</</Mixin.perform@https://test.perio.do/dist/periodo-2.1.0.min.js:71:14540[261]</ReactDefaultBatchingStrategy.batchedUpdates@https://test.perio.do/dist/periodo-2.1.0.min.js:67:5164batchedUpdates@https://test.perio.do/dist/periodo-2.1.0.min.js:70:16563[270]</ReactEventListener.dispatchEvent@https://test.perio.do/dist/periodo-2.1.0.min.js:68:3383

**Comment by ptgolden** [comment]
I spotted the problem. It should be fixed now. Can you two confirm?

**Comment by ptgolden** [comment]
(fixed by 5a6b3a91ed19aaff01b24d0efba923afcdad47e4)

**Comment by atomrab** [comment]
Sarah edited a period with an alt-label successfully yesterday, so yes, confirmed.
