### ISSUE TITLE
Problem with adding collection with no periods

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-client#88]
I've added an ARIADNE collection as a placeholder in which to enter ARIADNE data that is being finalized. In adding a collection with no periods, however, my local backend breaks: the collection can't be represented if I navigate away from it and back to it, and there is no place where I can add a period. I submitted and merged a patch, so the collection exists in the canonical dataset, and when I sync the canonical to the local, I can add a period to the ARIADNE collection (it appears in the collection list with 0 periods, but of course not in the period list or any of the period facet menus).

Should we account for users who enter a local collection and then close the client before they add a period? Or should we make a prominent note somewhere that tells the user not to make a collection without immediately adding at least one period?

The period-less collection generates the following error when I attempt to sync:

Time: 9/4/2015, 6:13:51 AM
Version: 2.3.6
# Page: #/p/ariadne/sync/

TypeError: Invalid attempt to destructure non-iterable instance
    at _slicedToArray (https://test.perio.do/dist/periodo-2.3.6.min.js:78:12335)
    at module.exports.React.createClass.getHiddenRange (https://test.perio.do/dist/periodo-2.3.6.min.js:78:13501)
    at module.exports.React.createClass.render (https://test.perio.do/dist/periodo-2.3.6.min.js:78:14712)
    at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (https://test.perio.do/dist/periodo-2.3.6.min.js:66:187)
    at ReactCompositeComponentMixin._renderValidatedComponent (https://test.perio.do/dist/periodo-2.3.6.min.js:66:606)
    at wrapper [as _renderValidatedComponent](https://test.perio.do/dist/periodo-2.3.6.min.js:69:8330)
    at ReactCompositeComponentMixin._updateRenderedComponent (https://test.perio.do/dist/periodo-2.3.6.min.js:65:31267)
    at ReactCompositeComponentMixin._performComponentUpdate (https://test.perio.do/dist/periodo-2.3.6.min.js:65:30839)
    at ReactCompositeComponentMixin.updateComponent (https://test.perio.do/dist/periodo-2.3.6.min.js:65:29682)
    at wrapper [as updateComponent](https://test.perio.do/dist/periodo-2.3.6.min.js:69:8330)

**Comment by rybesh** [comment]
I think we need to support the local creation of collections without definitions, although I don't see the value of actually accepting and merging patches that create new empty collections.

**Comment by atomrab** [comment]
I agree on both counts. I ran the patch through to see what would happen. Since it created the collection and allowed me to add a period to it, I think we already do support it -- the problem's on the local side, and this is certainly where it's more likely to affect the user.

**Comment by ptgolden** [comment]
This was fixed somewhere in the client rewrite
